### ISSUE TITLE
make 'manual Readinglist' manual

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#11]
after testing the currend manual readinglist Incarnation i come up with this suggestion
to improve functionality use instead of an select option element use a input with the currend (manual) chapter to edit it manually(focus and optional select). 

The manual readinglist is most the time used to mark the chapter ahead of the currend Novel.
Example case: Webnovel.com has a lot of paywall locked chapters ahead of the tracked chapter on Novelupdates (NU policy  no paywalled chapters)
Trial Marriage Husband: Need to Work Hard has over 1000 chapters but only 49 chapters listed

**Comment by Spark-NF** [comment]
So instead of a `select` with the next chapters as choices, have a free input?

AFAIK, the `select` only appears if the current entered value is an existing chapter on NovelUpdates, so not in the future, no? If you entered an invalid chapter, you wouldn't be able to edit the current chapter?

**Comment by SaltatorMortis** [comment]
jup the chapter isnt editable if you have a chapter not in the select list, you disable the edit function
my suggestion 'keep it manual' aka simple `<input>` element is because the transition from inside readinglist to outside readinglist is impossible, you cant enter a chapter manually in a `select` element.
the only way is a vue element with costum dropdown or make it a `input `element by default

PS suggestion based on latest stable version

**Comment by Spark-NF** [comment]
Actually, I fixed it by using an `<input>` for manual reading lists, but I feel that keeping the `<select>` can still be useful if the chapter you're currently reading is on NovelUpdates.

What do you think of something like this?
https://select2.org/tagging

_(which solves the "you cant enter a chapter manually in a select element")_

**Comment by SaltatorMortis** [comment]
jeah something like this would work. But maybe don't use this one, mainly because of the additional required Framework. I've seen a few of them are already written for Vue.

this kind of select/multiselect could maybe usefull for the Search.
ie as you type it suggest available Tags / filter live for the active 'group'
and you could use this to (temporarily) delete already set 'group' specific filter easyly this way. (delete the date restriction etc.)

sorry have not tested the latest dev versions, so i dont know how you exactly have implemented each feature(only a very rough estimate on the basis of the code)

**Comment by Spark-NF** [comment]
Actually I'll just work on releasing 1.2.0 (Firefox support is pretty much broken right now), and if need be a new issue can be created later. but I'm not sure such feature would be _that_ helpful compared to embedding more libs and stuff.
