### ISSUE TITLE
'marking a chapter as read' only until popup closes

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#12]
the new "Don't reload the whole reading list when marking a chapter as read" is functioning fine, it only it isnt updating the `storage` properly.
if you update the readinglists frequently this results in no problem, you will only get one if you update it with a very slow frequently. (i.E. once three hours).

steps to reproduce:

> *  mark any chapter as read => the novel is properly updated (new releasecount not)
> *  reopen popup => you see the old readinglist progress until next update

PS. [offtopic] what version of node / jq / linux are you using? mine is always messing with your packagelock.json.

**Comment by Spark-NF** [comment]
Weird, that seems to be a bug regression as I'm sure I had fixed the problem, but when checking just now it's indeed there. I'll have a look and publish a 1.2.1 update when I'm done with a fix. 👍 

> PS. [offtopic] what version of node / jq / linux are you using? mine is always messing with your packagelock.json.

I use 1.5 and 1.6 interchangeably, and I'm on Windows. But `jq` doesn't touch `package-lock.json` and is only called if you do `npm run package`.

From what you're saying it sounds more like an `npm` thing. Having changes in your `package-lock.json` is normal when you do `npm install`. I'd suggest, if want to make sure to use exactly the same packages as I do, to do `npm ci` instead, which won't change your `package-lock.json` file ([more info](https://docs.npmjs.com/cli/ci.html)).
