### ISSUE TITLE
error on next Reload when partially updating readinglist

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#14]
everytime when you partially  update your chapter of any novel, iE Chapter 15 to Chapter 20 of 30, you will get a error after the next Update until you restart the Extension or your Browser.
before the Update the right Url (/extnu/ url) is displayed in the Pupup.
 

looks like the building of `novel.next` fails.

**Comment by SaltatorMortis** [comment]
maybe look for this one into the popup.ts
for me its look like a getter gets saved, thus causes the problems after closing the popup (Dead object)

**Comment by Spark-NF** [comment]
Indeed, I guess when setting the current chapter, some corrupted data from the popup slips into the background data, causing the "dead object" error.

Steps to reproduce:
1. Open popup
2. Edit novel chapter to some other chapter (except latest)
3. Close popup
4. Wait for auto-refresh or re-open popup and click "Refresh"
5. Error
