### ISSUE TITLE
readinglist filtered to 0 prevents popup from loading properly

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#16]
everytime the readinglist hits 0 the addon stops displaying the popup properly
it still gets an update on opening the popup/ when the countdown hits 0
but a blank white screen is displayed, the labes is stuck in the last state with a additional  `<unavailable>` from the vue.min in the console

a workaround fix for this is to add a ||[] to the fetching process of the readinglist
`popup.ts 102`
`const novels = await background$1.getReadingList()||[];`

**Comment by Spark-NF** [comment]
I never have 0 results, so I didn't notice that, good catch!

For some reason I had it return `undefined` for empty results, which doesn't make sense compared to an empty array. I guess that was some old stuff I forgot to remove. 🤔

**Comment by SaltatorMortis** [comment]
i too never hit 0
but to find the source from the dead object from the other bug I created a readinglist with 1 object (to reduce networkload for NU from the permanent restarting)
and then later added accidentally a everytime false rule (age smaller than 0)
thus i found this one..

thanks for fixing all the bugs i find..
keep your good work up..
