### ISSUE TITLE
Firefox requires it to be signed to install from file.

### ISSUE THREAD

**Issue by Tenome** [Spark-NF/firefox-novel-updates#25]
I tried installing the xpi from file in the Add-ons Manager, but it refuses to install and redirects me to this page instead.
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by Spark-NF** [comment]
Indeed, you might need to install it in debug mode since it's not signed. I'll see if I can start signing them in Github.
Any reason you're not  just installing it from the [Firefox add-ons website](https://addons.mozilla.org/en-US/firefox/addon/novel-updates-notifier/)?

**Comment by Tenome** [comment]
Ah, my bad, that didn't show up when I tried to search for it. You can ignore this then lol
