### ISSUE TITLE
dont force reload when marking chapter as read

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#3]
maybe to use the asynchonity to its fullest update the readinglist only 'onunload' of the window.

to visualize if a Novel has changes maybe the 'badge-primary' could be used color-coded (yellow pending, red failed, greed succeeded)

**Comment by Spark-NF** [comment]
Not sure about the `onunload` suggestion, but I guess that changing the read chapter shouldn't require a full list reload. Simply locking the relevant novel line and reloading it in the background should be enough.

**Comment by SaltatorMortis** [comment]
jeah your right
a line updade would do it to..
my suggestion was simply only to `markChapterRead` and then only update the readinglist in the background upon closing of the popup. 

i really need to work on my Idea to (understandable) suggestion process
ps keep your work up and thanks
