### ISSUE TITLE
add shortcut for "I read the last chapter"

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#5]
add a way to mark the currend chapter via a singleclick

maybe add a button under/edit the `editReadButton` to fast mark the current (latest) Chapter as read

**Comment by Spark-NF** [comment]
Indeed, I can see a button with a "check" (✔️) icon next to the other ones to say "I catched up to the latest chapter". I'll work on that this afternoon, I was already planning to finish up your first suggestion.
