### ISSUE TITLE
lost connection breaks Refresh Interval

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#6]
everytime when you fail to connect to Novelupdates and dont pull your readinglist successfully the update Interval is disrupted and continues only on manual Refresh the Interval resumes.

i don't know it fhis is alreadyfixed with your rebuild but incase not i still report this

**Comment by Spark-NF** [comment]
Indeed, I can see how this could happen. 👍 

I'll have a look and make a fix before releasing [v1.1.0](https://github.com/Spark-NF/novel-updates-notifier/milestone/1) this week-end.
