### ISSUE TITLE
TypeError: novels is undefined

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#7]
after the Last update the addon doesnt load  the Readinglist
a login via addon is still possible 

tested with Firefox + chome

```
TypeError: novels is undefined
TypeError: can't access dead object
```

**Comment by Bionus** [comment]
Crap. I'll take a look

**Comment by Bionus** [comment]
Crap, I'll take a look

**Comment by Bionus** [comment]
Do you have the stack trace? (i.e. in which file/where in said file the error occurred)

**Comment by Spark-NF** [comment]
Crap, I'll take a look
Do you have the stack trace? (i.e. in which file/where in said file the error occurred)

_EDIT: sorry for the spam_

**Comment by Spark-NF** [comment]
Isn't "can't access dead object" a Selenium error message actually? 🤔 
I can't reproduce this on any of my computers / chrome / FF.

**Comment by Spark-NF** [comment]
Could it be that you have so many novels that keeping all of their chapters in memory would take too much RAM? How many novels do you have among all your reading lists?

**Comment by SaltatorMortis** [comment]
after addon reenabling:
```
18:04:00.515 Event received <unavailable>
amo-c08279ab41f512d05228.js:1:1256327
18:04:04.612 Warning: attempting to write 8559 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
18:04:04.868 Event received <unavailable> amo-c08279ab41f512d05228.js:1:1256327
18:04:04.957 TypeError: chromeWin.gBrowserInit is undefined[Weitere Informationen]
ext-webNavigation.js:128:1
18:04:25.867 CSI/start
m=consumer:73:260

```
after opening the popup

`18:04:27.428 TypeError: novels is undefined bundle.js:115:1 `


PS.
jeah it could be my blacklist thats causing the problems (PPS around 160)

**Comment by Spark-NF** [comment]
I'll try to add a few hundred novels with lots of chapters to my reading list to see if I can reproduce, then I'll push a fix and release v1.1.1 within the weekend.

Sorry and thanks for noticing it so fast! 😅

**Comment by SaltatorMortis** [comment]
hmm 
after a littlebit testing i found out with my Readinglist if i go above 18 Novels it "crashes"

**Comment by Bionus** [comment]
Ok so after some investigation there seems to be 3 things here:
* Some parsing error while loading the reading list or a novel's chapters cause the loading to fail (very likely a novel with only 1 chapter, or the extension's cache acting up)
* If you open the popup after a failed loading, it will try to show in an empty novel list, which causes the `TypeError: novels is undefined`
* If you open the popup before the loading is finished then close the popup, when the loading finishes it will cause a `TypeError: can't access dead object` which can be safely ignored (I'll try to make it not occur however)

**Comment by Spark-NF** [comment]
Ok so after some investigation there seems to be 3 things here:
* Some parsing error while loading the reading list or a novel's chapters cause the loading to fail (very likely is a loading error occurred while loading a novel's chapter)
* If you open the popup after a failed loading, it will try to show in an empty novel list, which causes the `TypeError: novels is undefined`
* If you open the popup before the loading is finished then close the popup, when the loading finishes it will cause a `TypeError: can't access dead object` which can be safely ignored (I'll try to make it not occur however)

_(so nothing to do with the number of novels in the list it would seem)_

**Comment by Spark-NF** [comment]
Note that I also improved the logging/reporting so if there are loading errors later, they'll be much more easily to investigate (because that was truly not obvious here). 👍
