### ISSUE TITLE
error with manual readinglist

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#8]
got another one... (i feel like a minesweeper Rat)
if you have a manual readinglist enabled an error is thrown
`Error loading reading list <unavailable>`

a check against `xml.getElementsByName('chk_mrl')[0].checked` should fix this

but my "simple hacky" solution is to check against my "Display Favorites on Main Page"
`if ( !((xml.getElementsByTagName('script')[37].innerText).match(/\['[^\]]+?\]/g)[0].match(/\d+/g).includes(id.toString())) ){ return novels };`

**Comment by Spark-NF** [comment]
Never heard of "manual reading lists" before, but yeah it indeed seems to be breaking the page parsing, as the table structure slightly changes. I'll look into it!

> i feel like a minesweeper Rat

Well that's great as with my own basic usage there are some use cases that I seem to miss 😅

**Comment by Spark-NF** [comment]
I just pushed a bunch of commits that should make manual reading lists support as good as "normal" reading lists.

However, I don't really understand the point of such reading lists. Because manually entering chapter names mean that you can't see which are the "next" chapters, etc. Also, since you have the list of all chapters available, why type it yourself?

May I ask what do you use them for? (if that's not too indiscreet) 🤔

**Comment by SaltatorMortis** [comment]
manual readinglists have its uses..
 - track chapters ahead of NU (like: patreon chapters, Webnovel.com paywall locked chapters)
 - an overview of novels on hold until a specific chapter
   - ie 120/30  120 is the last Chapter of the Novel and 30 the current

btw thanks for adding support for manual Readinglists
Keep your good project up...

**Comment by Bionus** [comment]
I see, thanks for the info! 👍 

I just published [v1.1.2](https://github.com/Spark-NF/novel-updates-notifier/releases/tag/v1.1.2) on both Chrome and Firefox, which should fix your issue with your manual reading lists (and hopefully other issues).

> btw thanks for adding support for manual Readinglists
> Keep your good project up...

No problem, thanks for your tickets!

**Comment by Spark-NF** [comment]
I see, thanks for the info! 👍 

I just published [v1.1.2](https://github.com/Spark-NF/novel-updates-notifier/releases/tag/v1.1.2) on both Chrome and Firefox, which should fix your issue with your manual reading lists (and hopefully other issues).

> btw thanks for adding support for manual Readinglists
> Keep your good project up...

No problem, thanks for your tickets!
